### ISSUE TITLE
Приватное API?

### ISSUE THREAD

**Issue by newonder** [yandexmobile/yandexmapkit-ios#139]
Здравствуйте. При валидации приложения в Apple имеем ворнинг о использовании приватного API по методу requestDidCancel:.

Делаем поиск по либам:

Binary file Pods/FlurrySDK/Flurry/libFlurry_4.2.4.a matches
Binary file Pods/YandexMapKit/libYandexMapKit.a matches

Что делать?

**Comment by likhogrud** [comment]
Исправлено в 1.0.6
