### ISSUE TITLE
URL схемы Yandex.Maps для IOS

### ISSUE THREAD

**Issue by ghost** [yandexmobile/yandexmapkit-ios#147]
Скажите, есть ли в IOS Yandex.Maps возможность задать url схему для построения маршрута между двумя точками? Например, такая возможность имеется в приложении Yandex.Navigator.

**Comment by hose314** [comment]
Привет, есть такая проблема:
Маршрут строится только тогда, когда карты открыты. При открытии карт для построением маршрута с холодного старта маршрут не строится. 

Спасибо.
