### ISSUE TITLE
x64 support

### ISSUE THREAD

**Issue by alkozin** [yandexmobile/yandexmapkit-ios#159]
Тема уже не раз обсуждалась. Но в связи с новостью от Apple о прекращении приема 32 битных приложений становится остро актуальной. https://developer.apple.com/news/?id=10202014a

"Starting February 1, 2015, new iOS apps uploaded to the App Store must include 64-bit support and be built with the iOS 8 SDK, included in Xcode 6 or later. To enable 64-bit in your project, we recommend using the default Xcode build setting of “Standard architectures” to build a single binary with both 32-bit and 64-bit code."

Можно попросить вас пересобрать? Пробки от Яндекс наше все.

**Comment by pocheshire** [comment]
@seeyu а можно узнать куда вы ее выложили? Здесь https://github.com/yandexmobile/yandexmapkit-ios только тестовый пример, а нужна сама .a библиотека

**Comment by alkozin** [comment]
@pocheshire Ставьте через cocoapods

**Comment by likhogrud** [comment]
@pocheshire На странице https://github.com/yandexmobile/yandexmapkit-ios/wiki/Добавление-Yandex-Map-Kit-в-проект описана инструкция по добавлению YandexMapKit вручную, в том числе указана ссылка для скачивания архива со статической библиотекой
