### ISSUE TITLE
Архив библиотеки с поддержкой arm64

### ISSUE THREAD

**Issue by pocheshire** [yandexmobile/yandexmapkit-ios#166]
Нужна непосредственно сама библиотека. В Wiki ссылка на архив не обновилась после апдейта тестового проекта (здесь https://github.com/yandexmobile/yandexmapkit-ios не то, что нужно. А нужно как в разделе «Вручную» в пункте 2 https://github.com/yandexmobile/yandexmapkit-ios/wiki/Добавление-Yandex-Map-Kit-в-проект)

**Comment by likhogrud** [comment]
Добрый день. Ссылку поправили.
