### ISSUE TITLE
Краш: YMKUserLocationController.m line 200 -[YMKUserLocationController userLocationIsVisible]

### ISSUE THREAD

**Issue by horovodovodo4ka** [yandexmobile/yandexmapkit-ios#167]
Версия 1.0.7 cocoapods

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x395effe6 objc_msgSend_stret + 5 **center**
1  Scout                          0x003e8099 -[YMKUserLocationController userLocationIsVisible](YMKUserLocationController.m:200)
2  Scout                          0x003e867d -[YMKUserLocationController locationAnnotationLocationWillChange](YMKUserLocationController.m:297)
3  Scout                          0x003e8c3b -[YMKUserLocationController observeValueForKeyPath:ofObject:change:context:](YMKUserLocationController.m:430)
4  Foundation                     0x2c548543 NSKeyValueNotifyObserver + 262
5  Foundation                     0x2c547b63 NSKeyValueWillChange + 566
6  Foundation                     0x2c534855 -[NSObject(NSKeyValueObserverNotification) willChangeValueForKey:] + 172
7  Foundation                     0x2c567ac1 _NSSetObjectValueAndNotify + 76
8  Scout                          0x003e9bb3 -[YMKUserLocationController setUserLocationToNext](YMKUserLocationController.m:707)
9  Scout                          0x003e8fef -[YMKUserLocationController locationManager:locationUpdatedTo:](YMKUserLocationController.m:501)
10 CoreLocation                   0x2bf87e53 (null) + 24358
11 CoreLocation                   0x2bf83383 (null) + 5206
12 CoreLocation                   0x2bf7cee1 (null) + 972
13 CoreFoundation                 0x2b88c25d __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
14 CoreFoundation                 0x2b88b521 __CFRunLoopDoBlocks + 216
15 CoreFoundation                 0x2b88a07b __CFRunLoopRun + 1714
16 CoreFoundation                 0x2b7d6b51 CFRunLoopRunSpecific + 476
17 CoreFoundation                 0x2b7d6963 CFRunLoopRunInMode + 106
18 GraphicsServices               0x32d3c1a9 GSEventRunModal + 136
19 UIKit                          0x2ee28c91 UIApplicationMain + 1440
20 Scout                          0x002045eb main (main.m:17)

**Comment by djmadcat** [comment]
Этой информации разработчикам будет недостаточно для установления причины проблемы.
Это все равно, что сказать "оно упало".

Необходимо:
* указать окружение: симулятор / модель девайса, версию OS
* предоставить пример кода, как используется
* описать последовательность действий, вызвавших ошибку

/cc #168, #169

**Comment by xbitstream** [comment]
Что касается примера кода, то если посмотреть стек, то видно, что пользовательского кода вообще не было, это внутренности библиотеки. 
Окружение...
http://crashes.to/s/125b44fdb2b

**Comment by donbobka** [comment]
:+1:
