### ISSUE TITLE
Краш YMKMapViewInternal.m line 2072 -[YMKMapViewInternal rotationAnchorPoint]

### ISSUE THREAD

**Issue by horovodovodo4ka** [yandexmobile/yandexmapkit-ios#168]
Версия 1.0.7 cocoapods

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x32cc9fe6 objc_msgSend_stret + 5 **annotationXYPoint**
1  Scout                          0x003ed04b -[YMKMapViewInternal rotationAnchorPoint](YMKMapViewInternal.m:2072)
2  Scout                          0x003ecc2f -[YMKMapViewInternal showZoomLevel:withZoomScale:atXYPoint:withInfo:](YMKMapViewInternal.m:1980)
3  Scout                          0x003ecf7d -[YMKMapViewInternal updateAfterScrollViewAction](YMKMapViewInternal.m:2047)
4  UIKit                          0x284d250d -[UIScrollView _endPanNormal:] + 1644
5  UIKit                          0x28633939 -[UIScrollView handlePan:] + 120
6  UIKit                          0x2862107f _UIGestureRecognizerSendActions + 294
7  UIKit                          0x284cf9ed -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 668
8  UIKit                          0x288e5951 ___UIGestureRecognizerUpdate_block_invoke661 + 48
9  UIKit                          0x284993c5 _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 216
10 UIKit                          0x2849733f _UIGestureRecognizerUpdate + 2950
11 UIKit                          0x284cdddd -[UIWindow _sendGesturesForEvent:] + 784
12 UIKit                          0x284cd6ad -[UIWindow sendEvent:] + 520
13 UIKit                          0x284a3fbd -[UIApplication sendEvent:] + 196
14 UIKit                          0x28717bb5 _UIApplicationHandleEventFromQueueEvent + 14164
15 UIKit                          0x284a2a07 _UIApplicationHandleEventQueue + 1350
16 CoreFoundation                 0x24f66237 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
17 CoreFoundation                 0x24f6564b __CFRunLoopDoSources0 + 222
18 CoreFoundation                 0x24f63cc9 __CFRunLoopRun + 768
19 CoreFoundation                 0x24eb0b51 CFRunLoopRunSpecific + 476
20 CoreFoundation                 0x24eb0963 CFRunLoopRunInMode + 106
21 GraphicsServices               0x2c4161a9 GSEventRunModal + 136
22 UIKit                          0x28502c91 UIApplicationMain + 1440
23 Scout                          0x002355eb main (main.m:17)

**Comment by xbitstream** [comment]
Подробный отчет http://crashes.to/s/a252be5e7c1
