### ISSUE TITLE
Краш YMKUserLocationController.m line 633 -[YMKUserLocationController stopAnimating]

### ISSUE THREAD

**Issue by horovodovodo4ka** [yandexmobile/yandexmapkit-ios#169]
Версия 1.0.7 cocoapods

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x3771ef46 objc_msgSend + 5 **setAlignCenter:**
1  Scout                          0x00351879 -[YMKUserLocationController stopAnimating](YMKUserLocationController.m:633)
2  Scout                          0x003518db -[YMKUserLocationController animateUserLocationToNext](YMKUserLocationController.m:641)
3  Scout                          0x00350fef -[YMKUserLocationController locationManager:locationUpdatedTo:](YMKUserLocationController.m:501)
4  CoreLocation                   0x29f3bf43 (null) + 24398
5  CoreLocation                   0x29f37463 (null) + 5230
6  CoreLocation                   0x29f30f99 (null) + 972
7  CoreFoundation                 0x29842fe5 **CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK** + 12
8  CoreFoundation                 0x298422a9 __CFRunLoopDoBlocks + 216
9  CoreFoundation                 0x29840de3 __CFRunLoopRun + 1714
10 CoreFoundation                 0x2978e3b1 CFRunLoopRunSpecific + 476
11 CoreFoundation                 0x2978e1c3 CFRunLoopRunInMode + 106
12 GraphicsServices               0x30dbb201 GSEventRunModal + 136
13 UIKit                          0x2cdf843d UIApplicationMain + 1440
14 Scout                          0x0016c5eb main (main.m:17)

**Comment by xbitstream** [comment]
Подробный отчет
http://crashes.to/s/f9a557008d8

**Comment by donbobka** [comment]
:+1:
