### ISSUE TITLE
Вопрос по поводу отображения многоугольников

### ISSUE THREAD

**Issue by vertuozzo** [yandexmobile/yandexmapkit-ios#17]
Скажите, есть ли возможность отображать многоугольники на карте при помощи YandexMapKit?
Например - http://api.yandex.ru/maps/jsapi/doc/dg/tasks/how-to-add-polygon.xml

**Comment by zzasdee** [comment]
Вопрос всё ещё актуален. Есть какие-то подвижки по этому поводу?

**Comment by cooler333** [comment]
+1
