### ISSUE TITLE
CRITICAL (!) - Crash при обращении к методу region или setRegion при билде на iOS 8.3 SDK

### ISSUE THREAD

**Issue by OneSman7** [yandexmobile/yandexmapkit-ios#171]
Падение с EXC_BAD_ACCESS или EXC_BREAKPOINT
На симуляторе не проявляется. Только на железе.
Пользоваться стало невозможно.

**Comment by asidden** [comment]
аналогичный крэш, видимо, какие-то изменения в sdk 8.3

**Comment by Subloran** [comment]
То же самое

**Comment by khramtsou** [comment]
Падало на 8.1.3 и 8.3, поэтому откатился на XCode 6.2, clean build, работает.
https://developer.apple.com/downloads/

**Comment by OneSman7** [comment]
Падает на любой iOS при компиляции на iOS 8.3 SDK.
Вы по сути вернулись к билду на iOS 8.2 SDK.
Как временный костыль на несколько дней/недель это сойдет, можно даже скачать XCode 6.2, но не ставить его, а добавить iOS 8.2 SDK из него в XCode 6.3.

НО, так мы застреваем на iOS 8.2 SDK, теряем поддержку всех будущих SDK. Поэтому считаю, что этот баг критический и должен быть исправлен авторами: как они обещали.

**Comment by pashaisthebest** [comment]
Подтверждаю. Кстати зависит только от архитектуры а не от SDK, падает только на 64 битах, на 32 битах и 8.3 sdk не падает.

**Comment by romabakenbard** [comment]
проблема именно в setRegion
обошлось вот такими костылями:
есть метод convertLLToMapView
и делаем цикл с максимального зума до минимального, пока полученные координаты не будут влезать в экран
Решение конечно не очень красивое, зато проблема решилась

**Comment by westyeast** [comment]
Такая же ситуация.

**Comment by likhogrud** [comment]
Исправлено в 1.0.8

**Comment by asidden** [comment]
@likhogrud спасибо за исправление, а когда мы получим к нему доступ? :)

**Comment by khramtsou** [comment]
> pod update
Installing YandexMapKit 1.0.8 (was 1.0.7)

**Comment by asidden** [comment]
@khramtsou , спасибо - я только на список тэгов посмотрел, что он пустой
