### ISSUE TITLE
Compilation erro while simple import

### ISSUE THREAD

**Issue by k06a** [yandexmobile/yandexmapkit-ios#173]
This code can not be compiled:
```
#import <YandexMapKit/YandexMapKit.h>
```

But this works fine:
```
#import <UIKit/UIKit.h>
#import <YandexMapKit/YandexMapKit.h>
```

Looks like you forgot to import `UIKit` in some classes where uses `UIImage` and etc.

**Comment by djmadcat** [comment]
Duplicated #163

**Comment by k06a** [comment]
@djmadcat Ok!
