### ISSUE TITLE
Wrong map region on iOS 8.3

### ISSUE THREAD

**Issue by k06a** [yandexmobile/yandexmapkit-ios#174]
My code:
```
YMKMapRegion r = self.mapView.region;
```
My debug: `(lldb) p r`
```
(YMKMapRegion) $0 = {
  center = (latitude = 0.19278194777698587, longitude = 37.618677287850467)
  span = (latitudeDelta = 180, longitudeDelta = 0.65656977891820134)
}
````

Look like a bug, when map is centered to Moscow :)

![img_1791](https://cloud.githubusercontent.com/assets/702124/7221257/217d11fa-e6ec-11e4-8fc1-5f8db0862b70.jpg)

**Comment by k06a** [comment]
Also missing `NSStringFromMapRegion` function :)

**Comment by Lapskaus** [comment]
YMKMapCoordinate mapCoordinate = YMKMapCoordinateMake(55.80369874, 37.8098495);
    YMKMapRegionSize mapRegionSize = YMKMapRegionSizeMake(0.18867558, 0.30544803);
    region = YMKMapRegionMake(mapCoordinate, mapRegionSize);


Only iOs 8.3. 
EXC_BAD_ACCESS

**Comment by k06a** [comment]
How it is possible to make a bug in struct init function?

**Comment by Lapskaus** [comment]
https://github.com/yandexmobile/yandexmapkit-ios/issues/171
same problem

**Comment by k06a** [comment]
@Lapskaus oh, can you try this? I am AFK.
```
YMKMapCoordinate mapCoordinate = (YMKMapCoordinate) {55.80369874, 37.8098495};
YMKMapRegionSize mapRegionSize = (YMKMapRegionSize) {0.18867558, 0.30544803};
region = (YMKMapRegion) {mapCoordinate, mapRegionSize};
```

**Comment by Lapskaus** [comment]
@k06a this option works, but exception raised if i call 
[YMKMapViewInternal setRegion:animated:]
with this region.

**Comment by likhogrud** [comment]
Исправлено в 1.0.8
