### ISSUE TITLE
[!] Error installing YandexMapKit

### ISSUE THREAD

**Issue by yudinm** [yandexmobile/yandexmapkit-ios#177]
Здравствуйте.
Появилась следующая ошибка при pod install:

    [!] Error installing YandexMapKit
    [!] /usr/bin/unzip /var/folders/zj/g2pvqy816bs89n4mz6j0wwlc0000gq/T/d20150722-28399-9ysd83/file.zip -d /var/folders/zj/g2pvqy816bs89n4mz6j0wwlc0000gq/T/d20150722-28399-9ysd83

    Archive:  /var/folders/zj/g2pvqy816bs89n4mz6j0wwlc0000gq/T/d20150722-28399-9ysd83/file.zip
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of /var/folders/zj/g2pvqy816bs89n4mz6j0wwlc0000gq/T/d20150722-28399-9ysd83/file.zip or
            /var/folders/zj/g2pvqy816bs89n4mz6j0wwlc0000gq/T/d20150722-28399-9ysd83/file.zip.zip, and cannot find /var/folders/zj/g2pvqy816bs89n4mz6j0wwlc0000gq/T/d20150722-28399-9ysd83/file.zip.ZIP, period.

Видимо, не получается скачать libYandexMapKit.a (329,3 MB). 

Судя по .podspec должно качаться отсюда: http://m.soft.yandex.ru/download/mapkit/ios-v5/yamapkit-file.zip, однако

    curl http://m.soft.yandex.ru/download/mapkit/ios-v5/yamapkit-file.zip

Выдает:

    <html>
    <head><title>301 Moved Permanently</title></head>
    <body bgcolor="white">
    <center><h1>301 Moved Permanently</h1></center>
    <hr><center>nginx/1.6.3</center>
    </body>
    </html>

Подскажите пожалуйста, это временно?

**Comment by hellc** [comment]
_проблема та же постигла меня_

**Comment by megavolt605** [comment]
Может кто-нибудь выложить куда-нибудь для скачивания 1.0.8, пока Яндекс разбирается с редиректом ссылки из Pods?

**Comment by yudinm** [comment]
> megavolt605
> Может кто-нибудь выложить куда-нибудь для скачивания 1.0.8, пока Яндекс разбирается с редиректом ссылки из Pods?

Чтобы успешно прошел pod install, надо переложить pod в локальный репозиторий, а ссылку на zip с ресурсами подставлить в локальный spec? Может можно элегантней как-то провернуть?

В zip, как я понимаю только это:

    Pods/YandexMapKit/libYandexMapKit.a
    Pods/YandexMapKit/LICENSE.txt
    Pods/YandexMapKit/YandexMapKit_iOS7.bundle
    Pods/YandexMapKit/YandexMapKit.bundle

**Comment by Quarezz** [comment]
+1

**Comment by yudinm** [comment]
В /.cocoapods/repos/master/Specs/YandexMapKit/1.0.8/YandexMapKit.podspec.json заменил

     http://m.soft.yandex.ru/download/mapkit/ios-v5/yamapkit-file.zip

На

     https://dl.dropboxusercontent.com/u/6458378/yamapkit-file.zip

**Comment by megavolt605** [comment]
А то, что там 1.0.5 в YMKVersion.h - это как?
```
/*
 * YMKVersion.h
 *
 * This file is a part of the Yandex Map Kit.
 *
 * Version for iOS © 2010-2013 YANDEX
 *
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://legal.yandex.ru/mapkit/
 */

#ifndef __YMK_VERSION_H__
#define __YMK_VERSION_H__

#define YMK_VERSION_MAJOR 1
#define YMK_VERSION_MINOR 0
#define YMK_VERSION_PATCH 5

#define YMK_BUILD_NUMBER 540

#endif // __YMK_VERSION_H__
```

**Comment by yudinm** [comment]
Скорее всего с тех пор этот файлик не обновлялся. Кто в него заглядывал до сегодняшнего дня?)

**Comment by megavolt605** [comment]
Вот, добрый человек дал (вроде) 1.0.8. На 64bit компилируется (значит свежая, до 1.0.7 не было 60бит внутри), баги c setRegion нет.
https://drive.google.com/file/d/0B1n_tIcN8yMET3R3MGxzYk9hYTg/view?usp=sharing

**Comment by yudinm** [comment]
Ну тут тоже вроде бы 1.0.5

    /*
    * YMKVersion.h
    *
    * This file is a part of the Yandex Map Kit.
    *
    * Version for iOS © 2010-2013 YANDEX
    *
    * You may not use this file except in compliance with the License.
    * You may obtain a copy of the License at http://legal.yandex.ru/mapkit/
    */

    #ifndef __YMK_VERSION_H__
    #define __YMK_VERSION_H__
   
    #define YMK_VERSION_MAJOR 1
    #define YMK_VERSION_MINOR 0
    #define YMK_VERSION_PATCH 5

    #define YMK_BUILD_NUMBER 555

    #endif // __YMK_VERSION_H__

Но билд свежее, значит это действительно 1.0.8. А у меня, видимо, 1.0.7 осталось. Ну и хрен с ним.

**Comment by likhogrud** [comment]
Произошло недоразумение, прибили сервер где раньше лежал архив мапкита.
Выложил его на другой ресурс, так что pod update до 1.0.9

**Comment by Petro-Lomaka** [comment]
@likhogrud Та же ошибка что и у топик стартера.
 Снова ошибка сервера ?
