### ISSUE TITLE
Xcode setting ENABLE_BITCODE

### ISSUE THREAD

**Issue by vmalov** [yandexmobile/yandexmapkit-ios#180]
Под Xcode 7 выдает такое
`ld: '.../Pods/YandexMapKit/libYandexMapKit.a(YMKStartupRequest.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7`

На SO предлагают отключать BITCODE для конкретных таргетов, но YMK как таргет в подах не виден.

**Comment by vmalov** [comment]
Окей, это решается отключением bitcode для всего приложения, но это тоже так себе метод

**Comment by likhogrud** [comment]
Исправлено в 1.0.10
