### ISSUE TITLE
YMKMapView inheritance issue

### ISSUE THREAD

**Issue by adastreamer** [yandexmobile/yandexmapkit-ios#181]
Проблемы с расширением класса YMKMapView.
При попытке расширить класс с помощью категории, возникает такая ошибка: https://goo.gl/mVQXvV
Решается таким образом - https://github.com/adastreamer/yamapkit/commit/621902cb394b111451b5e8bf312b682e9ce6f122
Добавьте, пожалуйста, данный фикс в релиз.

**Comment by djmadcat** [comment]
Дубликат #163

**Comment by adastreamer** [comment]
@djmadcat давние еще тикеты. пора бы пофиксить :-)

**Comment by adastreamer** [comment]
@djmadcat а почему у вас нет отдельного репозитория под мапкит? мб быстрее дела бы шли пулл-реквестами

**Comment by adastreamer** [comment]
@djmadcat пардон, если вы не имеете отношения к Яндекс, не обратил внимание :-)

**Comment by djmadcat** [comment]
@adastreamer Не являюсь разработчиком. Просто слежу за проектом=) Помогаю иногда искать дубликаты.

Скорее всего исходники не открыты потому, что дело в приватных реализациях, раскрывающих тайны работы с картами. Ну тупо чтобы не использовали во зло, нарушая соглашения Яндекса с поставщиками карт, например.
Если несложно, можно issue закрыть. Кросслинк уже есть.
