### ISSUE TITLE
Мож UIKit заимпортить надо, или нунах?

### ISSUE THREAD

**Issue by olSolo** [yandexmobile/yandexmapkit-ios#183]
![screen shot 2015-11-23 at 15 34 59](https://cloud.githubusercontent.com/assets/4682149/11336747/e5c54868-91f8-11e5-8387-345e53433865.png)

**Comment by djmadcat** [comment]
Дубликат #163
Огромная просьба пользоваться поиском и не плодить дубликаты.
И, если возможно, закрыть этот issue=)
Спасибо=)

P.S. Нет, я не являюсь разработчиком Yandex MapKit.
