### ISSUE TITLE
ошибка yandex::maps::mapkit::images::PolylineImageAtlas::add <error>: Width of pattern is equal to 268, but should be power of 2. Added transparent padding

### ISSUE THREAD

**Issue by aposnov** [yandexmobile/yandexmapkit-ios#213]
ошибка yandex::maps::mapkit::images::PolylineImageAtlas::add <error>: Width of pattern is equal to 268, but should be power of 2. Added transparent padding

что она означает? и как ее исправить?)

**Comment by adminant** [comment]
Как исправить эту ошибку?

**Comment by aposnov** [comment]
@adminant попробуй вызвать метод в главном потоке dispatch.main.async или dispatch.main.asyncafter

**Comment by georrge1994** [comment]
такая же проблема, но на android. В чем именно проблема и как ее решает dispatch.main.async?

**Comment by AdislanSaidov** [comment]
та же проблема на android

**Comment by alexandertopskiy** [comment]
такая же проблема на mapkit для ios

**Comment by AlexSuvorov2k** [comment]
Всё ещё появляется на Android.

**Comment by berdibekovaG** [comment]
на flutter 3.7.1 появляется до сих пор
