### ISSUE TITLE
How to disable YMK logging?

### ISSUE THREAD

**Issue by yvasileuski** [yandexmobile/yandexmapkit-ios#31]
It is very annoying to find my own debug logging information among plenty of YMK dummy (for me) messages.

**Comment by ivoneug** [comment]
Hi there! Currently I'm facing the same issue, a lot of warn messages from YMK. I tried to turn them off using info from this issue, but there is no YMKConsoleLogging.h in YMK anymore. How can we turn off log messages nowadays?
