### ISSUE TITLE
Заменить на правильные слова результат обращения к геокодеру яндекса

### ISSUE THREAD

**Issue by virt87** [yandexmobile/yandexmapkit-ios#73]
Здравствуйте.При обращении к геокодеру яндекса и возвращении данных в формате json слова выдаются в виде \U041c\U043e\U0441\U043a\U0432\U0430
В адресной строке браузера все хорошо.Использую apple-ский парсер json.Прочитал многочисленный форумы.Подскажите как решить проблему?Обязательно ли писать функцию,чтобы выводить правильно слова?

**Comment by djmadcat** [comment]
@virt87 Актуально? Если нет – можно закрыть=)
