### ISSUE TITLE
Крэши

### ISSUE THREAD

**Issue by kohtenko** [yandexmobile/yandexmapkit-ios#84]
Несколько крешей связанных с картой (последняя точка в креш репорте),
 но сложно воспроизводимых повторно.

1)`-[YMMapOverlayView updateZOrder] (in MyApp) (YMMapOverlayView.m:157)`

2)
`-[KDViewController emitFlingGestureWithEvent:] (in MyApp) (KDViewController.mm:386)
-[KDViewController handlePanGesture:] (in MyApp) (KDViewController.mm:398)
-[KDViewController lastTouchLocationAtIndex:] (in MyApp) (KDViewController.mm:698)
+[YMKRouteLabelsOptimizer optimizeRouteLabelsDirections:zoomLevel:zoomScale:] (in MyApp) (YMKRouteLabelsOptimizer.mm:67)`

3)
`-[YMTile topLeftCoordinate] (in MyApp) (YMTile.m:74)
-[YMTile bottomRightCoordinate] (in MyApp) (YMTile.m:80)
-[YMKRouteSegment asCoreObject] (in MyApp) (YMKRouteSegment.mm:234)`

4)
`-[YMKRoutesManagerInternal performRouteRequest:] (in MyApp) (YMKRoutesManagerInternal.mm:247)
-[YMKRoutesManagerInternal performRouteRequest:] (in MyApp) (YMKRoutesManagerInternal.mm:249)
-[YMKMetaInformationParser convertFeatureIds:] (in MyApp) (YMKMetaInformationParser.mm:60)`

**Comment by djmadcat** [comment]
@kohtenko Проблема исправлена? Связанная задача закрыта на версии 1.0.4 еще 2013.01.31

**Comment by kohtenko** [comment]
Понятия не имею) Я комментарий писал 3 года назад, для меня это как минимум не актуально.

**Comment by djmadcat** [comment]
Закрываю как неактуальную и устаревшую.
